# Generated by Django 4.2.7 on 2023-11-16 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='surgery_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('case_number', models.IntegerField()),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('surgeon_name_1', models.CharField(max_length=100)),
                ('surgeon_name_2', models.CharField(max_length=100)),
                ('assistant_surgeon_name_1', models.CharField(max_length=100)),
                ('assistant_surgeon_name_2', models.CharField(max_length=100)),
                ('assistant_surgeon_name_3', models.CharField(max_length=100)),
                ('port_side_nurse_names', models.CharField(max_length=100)),
                ('surgery_name', models.CharField(max_length=100)),
                ('surgery_start_time', models.DateTimeField()),
                ('surgery_end_time', models.DateTimeField()),
                ('system_on_time', models.DateTimeField()),
                ('system_off_time', models.DateTimeField()),
                ('draping_start_time', models.DateTimeField()),
                ('draping_end_time', models.DateTimeField()),
                ('docking_start_time', models.DateTimeField()),
                ('docking_end_time', models.DateTimeField()),
                ('Instrument_used_1', models.CharField(choices=[('LND', 'Large needle driver'), ('MCS', 'Monopoler curved siccors')], max_length=3)),
                ('case_converted', models.BooleanField()),
                ('Instrument_issue', models.CharField(choices=[('0', 'No issue'), ('1', 'Issue 1'), ('2', 'Issue 2'), ('3', 'Issue 3'), ('4', 'Issue 4')], max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
