# Generated by Django 4.2.7 on 2023-11-20 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Hospitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hospital_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Instruments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SurgicalProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surgical_procedure", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("case_no", models.IntegerField(blank=True, null=True)),
                ("date_of_admission", models.DateTimeField(blank=True, null=True)),
                ("date_of_surgery", models.DateTimeField(blank=True, null=True)),
                (
                    "surgeon_name_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "surgeon_name_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assistant_surgeon_name_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assistant_surgeon_name_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assistant_surgeon_name_3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("patient_in_time", models.TimeField(blank=True, null=True)),
                ("patient_out_time", models.TimeField(blank=True, null=True)),
                ("system_on_time", models.TimeField(blank=True, null=True)),
                ("system_off_time", models.TimeField(blank=True, null=True)),
                ("draping_start_time", models.TimeField(blank=True, null=True)),
                ("draping_end_time", models.TimeField(blank=True, null=True)),
                ("patient_incision_time", models.TimeField(blank=True, null=True)),
                ("patient_skin_closure_time", models.TimeField(blank=True, null=True)),
                ("port_placement_start_time", models.TimeField(blank=True, null=True)),
                (
                    "cart_pos_and_doc_start_timem",
                    models.TimeField(blank=True, null=True),
                ),
                ("cart_pos_and_doc_end_time", models.TimeField(blank=True, null=True)),
                ("console_start_time", models.TimeField(blank=True, null=True)),
                ("console_end_time", models.TimeField(blank=True, null=True)),
                (
                    "console_interruption_time",
                    models.IntegerField(blank=True, null=True),
                ),
                ("cart_undock_start_time", models.IntegerField(blank=True, null=True)),
                ("cart_undock_end_time", models.IntegerField(blank=True, null=True)),
                (
                    "instrument_used_1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AAA", "instrument 1"),
                            ("AAB", "instrument 2"),
                            ("AAC", "instrument 3"),
                            ("AAD", "instrument 4"),
                            ("AAE", "instrument 5"),
                            ("AAF", "instrument 6"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "instrument_used_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AAA", "instrument 1"),
                            ("AAB", "instrument 2"),
                            ("AAC", "instrument 3"),
                            ("AAD", "instrument 4"),
                            ("AAE", "instrument 5"),
                            ("AAF", "instrument 6"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "instrument_used_3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AAA", "instrument 1"),
                            ("AAB", "instrument 2"),
                            ("AAC", "instrument 3"),
                            ("AAD", "instrument 4"),
                            ("AAE", "instrument 5"),
                            ("AAF", "instrument 6"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "instrument_used_4",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AAA", "instrument 1"),
                            ("AAB", "instrument 2"),
                            ("AAC", "instrument 3"),
                            ("AAD", "instrument 4"),
                            ("AAE", "instrument 5"),
                            ("AAF", "instrument 6"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "instrument_used_5",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AAA", "instrument 1"),
                            ("AAB", "instrument 2"),
                            ("AAC", "instrument 3"),
                            ("AAD", "instrument 4"),
                            ("AAE", "instrument 5"),
                            ("AAF", "instrument 6"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "cart_issue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("000", "cart issue 1"),
                            ("001", "cart issue 2"),
                            ("002", "cart issue 3"),
                            ("003", "cart issue 4"),
                            ("004", "cart issue 5"),
                            ("005", "cart issue 6"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "device_issue",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("000", "device issue 1"),
                            ("001", "device issue 2"),
                            ("002", "device issue 3"),
                            ("003", "device issue 4"),
                            ("004", "device issue 5"),
                            ("005", "device issue 6"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "device_patient_complications",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_discharge", models.DateTimeField(blank=True, null=True)),
                ("length_of_stay", models.DurationField(blank=True, null=True)),
                ("readmission", models.BooleanField(blank=True, null=True)),
                (
                    "post_discharge_complications",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "surgical_steps",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("total_blood_loss", models.IntegerField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="form.diagnosis",
                    ),
                ),
                (
                    "hospital_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="form.hospitals",
                    ),
                ),
                (
                    "instrument_test",
                    models.ManyToManyField(
                        related_name="instruments", to="form.instruments"
                    ),
                ),
                (
                    "surgical_procedure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="form.surgicalprocedure",
                    ),
                ),
            ],
        ),
    ]
