# Generated by Django 4.1.13 on 2023-11-23 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartIssues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceIssues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Hospitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentIssues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Instruments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SurgicalProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.CharField(max_length=100)),
                ("patient_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("age", models.IntegerField()),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("diagnosis", models.CharField(max_length=100)),
                ("case_no", models.IntegerField()),
                ("date_of_admission", models.DateTimeField(blank=True, null=True)),
                ("date_of_surgery", models.DateTimeField()),
                (
                    "surgeon_name_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "surgeon_name_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assistant_surgeon_name_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assistant_surgeon_name_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("patient_in_time", models.TimeField(blank=True, null=True)),
                ("patient_out_time", models.TimeField(blank=True, null=True)),
                ("system_on_time", models.TimeField()),
                ("system_off_time", models.TimeField()),
                ("draping_start_time", models.TimeField(blank=True, null=True)),
                ("draping_end_time", models.TimeField(blank=True, null=True)),
                ("patient_incision_time", models.TimeField(blank=True, null=True)),
                ("patient_skin_closure_time", models.TimeField(blank=True, null=True)),
                ("port_placement_start_time", models.TimeField(blank=True, null=True)),
                (
                    "cart_pos_and_doc_start_timem",
                    models.TimeField(blank=True, null=True),
                ),
                ("cart_pos_and_doc_end_time", models.TimeField(blank=True, null=True)),
                ("console_start_time", models.TimeField(blank=True, null=True)),
                ("console_end_time", models.TimeField(blank=True, null=True)),
                (
                    "console_interruption_time",
                    models.IntegerField(blank=True, null=True),
                ),
                ("cart_undock_start_time", models.IntegerField(blank=True, null=True)),
                ("cart_undock_end_time", models.IntegerField(blank=True, null=True)),
                ("instrument_1_id", models.IntegerField(blank=True, null=True)),
                ("instrument_2_id", models.IntegerField(blank=True, null=True)),
                ("instrument_3_id", models.IntegerField(blank=True, null=True)),
                ("instrument_4_id", models.IntegerField(blank=True, null=True)),
                ("instrument_5_id", models.IntegerField(blank=True, null=True)),
                ("case_converted", models.BooleanField(blank=True, null=True)),
                (
                    "cart_issue_remark",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "device_issue_remark",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "instrument_issue_remark",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "device_patient_complications",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_discharge", models.DateTimeField(blank=True, null=True)),
                ("length_of_stay", models.DurationField(blank=True, null=True)),
                ("readmission", models.BooleanField(blank=True, null=True)),
                (
                    "post_discharge_complications",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("surgical_steps", models.TextField(blank=True, null=True)),
                ("total_blood_loss", models.IntegerField(blank=True, null=True)),
                ("additional_remark", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cart_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="form.cartissues",
                    ),
                ),
                (
                    "device_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="form.deviceissues",
                    ),
                ),
                (
                    "hospital_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="form.hospitals"
                    ),
                ),
                (
                    "instrument_issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="form.instrumentissues",
                    ),
                ),
                (
                    "instrument_used_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument1",
                        to="form.instruments",
                    ),
                ),
                (
                    "instrument_used_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument2",
                        to="form.instruments",
                    ),
                ),
                (
                    "instrument_used_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument3",
                        to="form.instruments",
                    ),
                ),
                (
                    "instrument_used_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument4",
                        to="form.instruments",
                    ),
                ),
                (
                    "instrument_used_5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instrument5",
                        to="form.instruments",
                    ),
                ),
                (
                    "surgical_procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="form.surgicalprocedure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instruments_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choices", models.ManyToManyField(to="form.instruments")),
            ],
        ),
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bug_text", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
