# Generated by Django 4.2.7 on 2023-11-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cart_issue_remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="device_issue_remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="instrument_issue_remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
