# Generated by Django 4.2.7 on 2023-11-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_post_cart_issue_remark_post_device_issue_remark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cart_issue_remark",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="device_issue_remark",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="instrument_issue_remark",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
